apiVersion: v1
kind: Service
metadata:
  name: certificate-backend-service
spec:
  selector:
    app: certificate-backend
  ports:
    - protocol: TCP
      port: 80
      targetPort: 5000
  type: LoadBalancer
